import enum

class MsEvDriverManagement(enum.Enum):
    DRIVER_VERIFICATION_REQUEST = "DriverVerificationRequest"
    DRIVER_VERIFICATION_RESPONSE = "DriverVerificationResponse"

class MsOrderManagement(enum.Enum):
    CREATE_ORDER = "CreateOrder"
    CREATE_ORDER_RESPONSE = "CreateOrderResponse"
    REJECT_ORDER = "RejectOrder"
    STOP_TRANSACTION = "StopTransaction"
    LIST_ORDER_REQUEST = "ListOrderRequest"
    LIST_ORDER_RESPONSE = "ListOrderResponse"

class MsPaymentManagement(enum.Enum):
    AUTHORIZE_PAYMENT_REQUEST = "AuthorizePaymentRequest"
    AUTHORIZE_PAYMENT_RESPONSE = "AuthorizePaymentResponse"
    CANCEL_PAYMENT_REQUEST = "CancelPaymentRequest"
    CANCEL_PAYMENT_RESPONSE = "CancelPaymentResponse"

class MsCSMSManagement(enum.Enum):
    SECURITY_REQUEST = "SecurityRequest"
    SECURITY_RESPONSE = "SecurityResponse"
    PROVISIONING_REQUEST = "ProvisioningRequest"
    PROVISIONING_RESPONSE = "ProvisioningResponse"
    AUTHORIZE_REQUEST = "AuthorizeRequest"
    AUTHORIZE_RESPONSE = "AuthorizeResponse"
    LOCAL_AUTHORIZATION_REQUEST = "LocalAuthorizationRequest"
    LOCAL_AUTHORIZATION_RESPONSE = "LocalAuthorizationResponse"
    REMOTE_CONTROL_REQUEST = "RemoteControlRequest"
    REMOTE_CONTROL_RESPONSE = "RemoteControlResponse"
    AVAILABILITY_REQUEST = "AvailabilityRequest"
    AVAILABILITY_RESPONSE = "AvailabilityResponse"
    RESERVATION_REQUEST = "ReservationRequest"
    RESERVATION_RESPONSE = "ReservationResponse"
    SMART_CHARGING_REQUEST = "SmartChargingRequest"
    SMART_CHARGING_RESPONSE = "SmartChargingResponse"
    FIRMWARE_REQUEST = "FirmwareRequest"
    FIRMWARE_RESPONSE = "FirmwareResponse"
    ISO15118_REQUEST = "ISO15118Request"
    ISO15118_RESPONSE = "ISO15118Response"
    DIAGNOSTICS_REQUEST = "DiagnosticsRequest"
    DIAGNOSTICS_RESPONSE = "DiagnosticsResponse"
    DATA_TRANSFER_REQUEST = "DataTransferRequest"
    DATA_TRANSFER_RESPONSE = "DataTransferResponse"

class MsEVSEManagement(enum.Enum):
    SECURITY_REQUEST = "MsEVSEManagementSecurityRequest"
    SECURITY_RESPONSE = "MsEVSEManagementSecurityResponse"
    PROVISIONING_REQUEST = "MsEVSEManagementProvisioningRequest"
    PROVISIONING_RESPONSE = "MsEVSEManagementProvisioningResponse"
    AUTHORIZE_REQUEST = "MsEVSEManagementAuthorizeRequest"
    AUTHORIZE_RESPONSE = "MsEVSEManagementAuthorizeResponse"
    LOCAL_AUTHORIZATION_REQUEST = "MsEVSEManagementLocalAuthorizationRequest"
    LOCAL_AUTHORIZATION_RESPONSE = "MsEVSEManagementLocalAuthorizationResponse"
    REMOTE_CONTROL_REQUEST = "MsEVSEManagementRemoteControlRequest"
    REMOTE_CONTROL_RESPONSE = "MsEVSEManagementRemoteControlResponse"
    AVAILABILITY_REQUEST = "MsEVSEManagementAvailabilityRequest"
    AVAILABILITY_RESPONSE = "MsEVSEManagementAvailabilityResponse"
    RESERVATION_REQUEST = "MsEVSEManagementReservationRequest"
    RESERVATION_RESPONSE = "MsEVSEManagementReservationResponse"
    SMART_CHARGING_REQUEST = "MsEVSEManagementSmartChargingRequest"
    SMART_CHARGING_RESPONSE = "MsEVSEManagementSmartChargingResponse"
    FIRMWARE_REQUEST = "MsEVSEManagementFirmwareRequest"
    FIRMWARE_RESPONSE = "MsEVSEManagementFirmwareResponse"
    ISO15118_REQUEST = "MsEVSEManagementISO15118Request"
    ISO15118_RESPONSE = "MsEVSEManagementISO15118Response"
    DIAGNOSTICS_REQUEST = "MsEVSEManagementDiagnosticsRequest"
    DIAGNOSTICS_RESPONSE = "MsEVSEManagementDiagnosticsResponse"
    DATA_TRANSFER_REQUEST = "MsEVSEManagementDataTransferRequest"
    DATA_TRANSFER_RESPONSE = "MsEVSEManagementDataTransferResponse"