"""empty message

Revision ID: 42c061c4d7e3
Revises: 
Create Date: 2024-05-15 09:11:55.028494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c061c4d7e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('charge_point_id', sa.String(length=50), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('ev_driver_id', sa.String(length=50), nullable=False),
    sa.Column('rfid', sa.String(length=50), nullable=False),
    sa.Column('tariff_id', sa.Integer(), nullable=False),
    sa.Column('is_charging', sa.Boolean(), nullable=False),
    sa.Column('is_reservation', sa.Boolean(), nullable=False),
    sa.Column('payment_required_ind', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('charged_energy', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('paid_by', sa.String(length=50), nullable=False),
    sa.Column('transaction_detail', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['order.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('order')
    # ### end Alembic commands ###
