"""empty message

Revision ID: 797f96349a4d
Revises: 91d3ef22ba02
Create Date: 2024-08-05 10:13:21.510234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797f96349a4d'
down_revision: Union[str, None] = '91d3ef22ba02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order', ['transaction_id'])
    op.add_column('transaction', sa.Column('meter_start', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('meter_interval', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('meter_stop', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'meter_stop')
    op.drop_column('transaction', 'meter_interval')
    op.drop_column('transaction', 'meter_start')
    op.drop_constraint(None, 'order', type_='unique')
    # ### end Alembic commands ###
