"""empty message

Revision ID: 8410d946ddfc
Revises: 0fdeb83eee86
Create Date: 2024-05-28 09:12:09.764228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8410d946ddfc'
down_revision: Union[str, None] = '0fdeb83eee86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'end_time')
    op.drop_column('transaction', 'start_time')
    # ### end Alembic commands ###
