"""empty message

Revision ID: d196053a8917
Revises: b4bcde215e4c
Create Date: 2024-05-17 15:34:58.604023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd196053a8917'
down_revision: Union[str, None] = 'b4bcde215e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('order', 'charge_point_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('order', 'connector_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'ev_driver_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('order', 'is_charging',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order', 'is_reservation',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order', 'requires_payment',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('order', 'create_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_unique_constraint(None, 'order', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='unique')
    op.alter_column('order', 'create_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'requires_payment',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order', 'is_reservation',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order', 'is_charging',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('order', 'ev_driver_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('order', 'connector_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'charge_point_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
