@startuml Order Service
title Order Service

boundary CSMSService        #Lavender
boundary MobileAppService   #Lavender
boundary EVSEMgmt           #Lavender
boundary OrderService       #LightSteelBlue
database OrderServiceDB     #LightSteelBlue
boundary EVDriverService    #Lavender
boundary PaymentService     #Lavender
group #LightBlue MobileUser
    MobileAppService -> OrderService: [API] MsOrderManagement.CreateOrder
else #CadetBlue OtherUser
    CSMSService -> OrderService: [Kafka] MsOrderManagement.CreateOrder
end
OrderService -> EVDriverService : [Kafka] MsEvDriverManagement.DriverVerificationRequest
EVDriverService -> EVDriverService : verify driver
EVDriverService -> OrderService : [Kafka] MsEvDriverManagement.DriverVerificationResponse
group #IndianRed DRIVER VERIFICATION FAILED
    group #LightBlue MobileUser
        OrderService -> EVSEMgmt: [Kafka] EVSEMgmt.AuthorizeResponse
    else #CadetBlue OtherUser
        OrderService -> CSMSService: [Kafka] CSMSService.AuthorizeResponse
    end
else #DarkSeaGreen DRIVER VERIFICATION SUCCESS
    group #LightSteelBlue PAYMENT_REQUIRED = FALSE
        group #LightBlue MobileUser    
                OrderService -> EVSEMgmt: [Kafka] EVSEMgmt.AuthorizeResponse
        else #CadetBlue OtherUser
            OrderService -> CSMSService: [Kafka] CSMSService.AuthorizeResponse
        end
    else #LightSteelBlue PAYMENT_REQUIRED = TRUE 
        EVDriverService -> PaymentService: [Kafka] MsPaymentService.AuthorizePaymentRequest
        group #DarkSeaGreen AUTHORIZE_PAYMENT = SUCCESS
            PaymentService --> OrderService: [Kafka] MsPaymentService.AuthorizePaymentResponse
        else #IndianRed AUTHORIZE_PAYMENT = FALSE
            PaymentService -> EVDriverService: [Kafka] MsPaymentService.AuthorizePaymentResponse
            EVDriverService -> OrderService: [Kafka] MsOrderManagement.RejectOrder
            group #LightBlue MobileUser    
                OrderService -> EVSEMgmt: [Kafka] EVSEMgmt.CancelTransaction
            else #CadetBlue OtherUser
                OrderService -> CSMSService: [Kafka] CSMSService.CancelTransaction
            end
        end
    end
end