@startuml Order Service
title Order Service

boundary CSMSService        #Lavender
boundary MobileAppService   #Lavender
boundary EVSEMgmt           #Lavender
boundary OrderService       #LightSteelBlue
database OrderServiceDB     #LightSteelBlue
boundary EVDriverService    #Lavender
boundary PaymentService     #Lavender
group #LightBlue Mobile
    MobileAppService -> OrderService: [API-API] CreateOrder
else #CadetBlue Web
    EVSEMgmt -> OrderService: [Kafka-Kafka] CreateOrder
end
OrderService -> EVDriverService : [Kafka-Kafka] DriverVerificationRequest
EVDriverService -> EVDriverService : verify driver
EVDriverService -> OrderService : [Kafka-Kafka] DriverVerificationResponse
group #IndianRed DRIVER VERIFICATION FAILED
    group #LightBlue MobileUser
        OrderService -> EVSEMgmt: [Kafka-Kafka] CreateOrderResponse
    else #CadetBlue OtherUser
        OrderService -> CSMSService: [Kafka-Kafka] CreateOrderResponse
    end
else #DarkSeaGreen DRIVER VERIFICATION SUCCESS
    group #LightSteelBlue requires_payment = FALSE
        group #LightBlue MobileUser    
                OrderService -> EVSEMgmt: [Kafka-Kafka] CreateOrderResponse
        else #CadetBlue OtherUser
            OrderService -> CSMSService: [Kafka-Kafka] CreateOrderResponse
        end
    else #LightSteelBlue requires_payment = TRUE 
        EVDriverService -> PaymentService: [Kafka-Kafka] AuthorizePaymentRequest
        group #DarkSeaGreen AUTHORIZE_PAYMENT = SUCCESS
            PaymentService --> OrderService: [Kafka-Kafka] AuthorizePaymentResponse
        else #IndianRed AUTHORIZE_PAYMENT = FALSE
            PaymentService -> EVDriverService: [Kafka-Kafka] AuthorizePaymentResponse
            EVDriverService -> OrderService: [Kafka-Kafka] RejectOrder
            group #LightBlue MobileUser    
                OrderService -> EVSEMgmt: [Kafka-Kafka] OrderRejected
            else #CadetBlue OtherUser
                OrderService -> CSMSService: [Kafka-Kafka] OrderRejected
            end
        end
    end
end