name: Run unit tests and sonarqube scan

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/**"
      - "releases/**/*"

jobs:
  unit_test:
    runs-on: self-hosted
    env: 
      MASTER_DB_SECRET_NAME: ${{ secrets.MASTER_DB_SECRET_NAME }}
      MASTER_DB_NAME: ${{ secrets.MASTER_DB_NAME }}
      MASTER_DB_PROXY: ${{ secrets.MASTER_DB_PROXY }}
      KAFKA_BOOTSTRAP_SERVER: ${{ secrets.KAFKA_BOOTSTRAP_SERVER }}
      KAFKA_SASL_USERNAME: ${{ secrets.KAFKA_SASL_USERNAME }}
      KAFKA_SASL_PASSWORD: ${{ secrets.KAFKA_SASL_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt --force-reinstall
      - run: pip install coverage pytest pytest-cov
      - run: coverage run -m pytest
      - run: coverage report
      - run: coverage xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: coverage.xml
          retention-days: 1
      # - uses: ./.github/actions/teams-notification
      #   with:
      #     MS_TEAMS_WEBHOOK_URI: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
      - name: Notify Successful
        if: ${{ success() }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: ${{ format('Successful | {0}:{1} | job:{2}', github.event_name, github.ref_name, github.job) }}
          notification-color: 28A745
          timezone: Asia/Singapore
          verbose-logging: false
      - name: Notify Failure
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: ${{ format('Failure | {0}:{1} | job:{2}', github.event_name, github.ref_name, github.job) }}
          notification-color: DC3545
          timezone: Asia/Singapore
          verbose-logging: false
      - name: Notify Cancelled
        if: ${{ cancelled() }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: ${{ format('Cancelled | {0}:{1} | job:{2}', github.event_name, github.ref_name, github.job) }}
          notification-color: FFC107
          timezone: Asia/Singapore
          verbose-logging: false

  sonarqube:
    needs: [unit_test]
    runs-on: self-hosted
    if: ${{ github.event_name == 'push' }}
    steps:
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1 
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: .
      - uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_ROOT_CERT: ${{ secrets.SONAR_ROOT_CERT }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=oneems_order_service
            -Dsonar.python.version=3.10
            -Dsonar.python.coverage.reportPaths=coverage.xml